# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "cr.hotio.dev/hotio/whisparr"
  amd64: "cr.hotio.dev/hotio/whisparr"
  armhf: "cr.hotio.dev/hotio/whisparr"
  armv7: "cr.hotio.dev/hotio/whisparr"
  i386: "cr.hotio.dev/hotio/whisparr"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Example add-on"
  org.opencontainers.image.description: "Example add-on to use as a blueprint for new add-ons."
  org.opencontainers.image.source: "https://github.com/home-assistant/addons-example"
  org.opencontainers.image.licenses: "Apache License 2.0"
