# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  # datasource=docker depName=hotio/whisparr
  aarch64: "ghcr.io/hotio/whisparr:nightly-2.0.0.131"
  # datasource=docker depName=hotio/whisparr
  amd64: "ghcr.io/hotio/whisparr:nightly-2.0.0.131"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Whisparr"
  org.opencontainers.image.description: "Whisparr."
  org.opencontainers.image.source: "https://github.com/monkey-debugger/monkeys-homeassistant-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
