# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "cr.hotio.dev/hotio/whisparr:nightly-0.1.0.47"
  amd64: "cr.hotio.dev/hotio/whisparr:nightly-0.1.0.47"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Whisparr"
  org.opencontainers.image.description: "Whisparr."
  org.opencontainers.image.source: "https://github.com/monkey-debugger/monkeys-homeassistant-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
