name: Whisparr
version: "nightly-0.1.0.27"
slug: whisparr
description: Whisparr
url: "https://github.com/monkey-debugger/monkeys-homeassistant-addons"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
apparmor: true
boot: "auto"
map:
  - "config:rw"
  - "share:rw"
  - "media:rw"
  - "ssl"
environment:
  "PGID": "0"
  "PUID": "0"
options:
  "PGID": 0
  "PUID": 0
  "cifspassword": "<password>"
  "cifsusername": "<username>"
  "networkdisks": "<//SERVER/SHARE>,<//SERVER2/SHARE2>"
ports:
  "9696/tcp": 9696
ports_description:
  "9696/tcp": "web interface"
privileged:
  - "SYS_ADMIN"
  - "DAC_READ_SEARCH"
schema:
  "PGID": "int"
  "PUID": "int"
  "TZ": "str?"
  "cifspassword": "str?"
  "cifsusername": "str?"
  "networkdisks": "str?"
  "smbv1": "bool?"
startup: "services"
upstream: "nightly-0.1.0.27"
webui: http://[HOST]:[PORT:6969]"
