name: Whisparr
# datasource=docker depName=hotio/whisparr
version: nightly-2.0.0.131
slug: whisparr
description: Whisparr
url: "https://github.com/monkey-debugger/monkeys-homeassistant-addons/tree/main/whisparr"
init: false
arch:
  - aarch64
  - amd64
map:
  - "config:rw"
  - "share:rw"
  - "media:rw"
  - "ssl"
environment:
  "PGID": "1000"
  "PUID": "1000"
options:
  "PGID": 0
  "PUID": 0
ports:
  "6969/tcp": 6969
ports_description:
  "6969/tcp": "web interface"
privileged:
  - "SYS_ADMIN"
  - "DAC_READ_SEARCH"
schema:
  "PGID": "int"
  "PUID": "int"
startup: "services"
webui: http://[HOST]:[PORT:6969]"
